### ISSUE TITLE
Pool master transfer will cause the client to crash when first run

### ISSUE THREAD

**Issue by wranders** [xcp-ng/xenadmin#100]
# Summary of Bug

In a pool, when placing the master into Maintenance Mode, a server which has never been elected or assigned master previously will cause XCP-ng Center to crash. After the initial crash, reelecting the first master and again electing the same second server to reproduce the failure results in expected behavior.

# Reproduction

1. Right click server designated as the pool master
2. Click `Enter Maintenance Mode...`
3. In the popup transfer window, select a server that has never been assigned master
4. Click `Enter Maintenance Mode`
5. Witness the transfer process appear to function properly until the client crashes roughly 3-4 seconds later

# Expected Behavior

When the new master is elected, the pool should temporarily appear to be unavailable, but will automatically reconnect in 60 seconds. Upon reconnect, the new master should appear active and the old master should appear to be in maintenance mode.

# Crash Log

```
2018-09-15 01:02:14,499 INFO  XenAPI.Session [19] - Invoking JSON-RPC method 'task.destroy'
2018-09-15 01:02:14,546 INFO  Audit [19] - Operation success: EvacuateHostAction: Ragnaros: Pool 4a73f152-d629-a472-2aee-a4caac53d2bc (Ragnaros): Host ac776fb9-1061-45d0-bc05-6a9da0fdbc68 (xcp02): Nominated server xcp03 as new master
2018-09-15 01:02:17,183 WARN  XenAdmin.Network.XenConnection [Connection to 192.168.5.65] - Lost connection to 192.168.5.65
2018-09-15 01:02:17,200 ERROR XenAdmin.Dialogs.LicenseStatus [9] - Couldn't get the server time because: Value cannot be null.
Parameter name: System.Object
2018-09-15 01:02:17,200 ERROR XenAdmin.Utils.AsyncServerTime [9] - Failed to fetch server time for host as host could not be resolved
2018-09-15 01:02:17,203 ERROR XenAdmin.Controls.MainWindowControls.NavigationView [Main program thread] - System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.TabPages.GeneralTabPage.PoolAdditionalLicenseString()
   at XenAdmin.TabPages.GeneralTabPage.generateGeneralBox()
   at XenAdmin.TabPages.GeneralTabPage.BuildList()
   at XenAdmin.TabPages.GeneralTabPage.set_XenObject(IXenObject value)
   at XenAdmin.MainWindow.TheTabControl_SelectedIndexChanged(Object sender, EventArgs e)
   at XenAdmin.MainWindow.navigationPane_TreeViewSelectionChanged()
   at XenAdmin.Controls.MainWindowControls.NavigationPane.navigationView_TreeViewSelectionChanged()
   at XenAdmin.Controls.MainWindowControls.NavigationView.treeView_SelectionsChanged(Object sender, EventArgs e)
   at XenAdmin.Controls.MultiSelectTreeView.OnSelectionsChanged()
   at XenAdmin.Controls.MultiSelectTreeView.MultiSelectTreeSelectedNodeCollection.SetContents(IEnumerable`1 items)
   at XenAdmin.Controls.FlickerFreeTreeView.RestoreSelection()
   at XenAdmin.Controls.FlickerFreeTreeView.EndUpdate()
   at XenAdmin.MainWindowTreeBuilder.RefreshTreeView(VirtualTreeNode newRootNode, String searchText, NavigationMode searchMode)
   at XenAdmin.Controls.MainWindowControls.NavigationView.<RefreshTreeView>b__63_0()
System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.TabPages.GeneralTabPage.PoolAdditionalLicenseString()
   at XenAdmin.TabPages.GeneralTabPage.generateGeneralBox()
   at XenAdmin.TabPages.GeneralTabPage.BuildList()
   at XenAdmin.TabPages.GeneralTabPage.set_XenObject(IXenObject value)
   at XenAdmin.MainWindow.TheTabControl_SelectedIndexChanged(Object sender, EventArgs e)
   at XenAdmin.MainWindow.navigationPane_TreeViewSelectionChanged()
   at XenAdmin.Controls.MainWindowControls.NavigationPane.navigationView_TreeViewSelectionChanged()
   at XenAdmin.Controls.MainWindowControls.NavigationView.treeView_SelectionsChanged(Object sender, EventArgs e)
   at XenAdmin.Controls.MultiSelectTreeView.OnSelectionsChanged()
   at XenAdmin.Controls.MultiSelectTreeView.MultiSelectTreeSelectedNodeCollection.SetContents(IEnumerable`1 items)
   at XenAdmin.Controls.FlickerFreeTreeView.RestoreSelection()
   at XenAdmin.Controls.FlickerFreeTreeView.EndUpdate()
   at XenAdmin.MainWindowTreeBuilder.RefreshTreeView(VirtualTreeNode newRootNode, String searchText, NavigationMode searchMode)
   at XenAdmin.Controls.MainWindowControls.NavigationView.<RefreshTreeView>b__63_0()
2018-09-15 01:02:17,209 ERROR XenAdmin.Program [Main program thread] - Exception in Invoke
System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.TabPages.GeneralTabPage.PoolAdditionalLicenseString()
   at XenAdmin.TabPages.GeneralTabPage.generateGeneralBox()
   at XenAdmin.TabPages.GeneralTabPage.BuildList()
   at XenAdmin.MainWindow.<UpdateHeaderAndTabPages>b__113_0()
   at XenAdmin.Program.Invoke(Control c, MethodInvoker f)
   at XenAdmin.MainWindow.UpdateHeaderAndTabPages()
   at XenAdmin.MainWindow.navigationPane_TreeViewRefreshed()
   at XenAdmin.Controls.MainWindowControls.NavigationPane.navigationView_TreeViewRefreshed()
   at XenAdmin.Controls.MainWindowControls.NavigationView.<RefreshTreeView>b__63_0()
   at XenAdmin.Program.<>c__DisplayClass64_0.<Invoke>b__0()
2018-09-15 01:02:17,209 ERROR XenAdmin.Program [13] - Exception in Invoke (ControlType=XenAdmin.MainWindow, MethodName=<RefreshTreeView>b__63_0)
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XenAdmin.Program.Invoke(Control c, MethodInvoker f)
2018-09-15 01:02:17,211 FATAL XenAdmin.Program [13] - Uncaught exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XenAdmin.Program.Invoke(Control c, MethodInvoker f)
   at XenAdmin.UpdateManager.OnUpdate(EventArgs e)
   at XenAdmin.UpdateManager.DoUpdate(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2018-09-15 01:02:17,211 INFO  XenAdmin.Program [13] - Version: 7.5.0.8
2018-09-15 01:02:17,211 INFO  XenAdmin.Program [13] - .NET runtime version: 4.0.30319.42000
2018-09-15 01:02:17,211 INFO  XenAdmin.Program [13] - OS version: Microsoft Windows NT 10.0.17134.0
2018-09-15 01:02:17,211 INFO  XenAdmin.Program [13] - UI Culture: English (United States)
2018-09-15 01:02:17,211 INFO  XenAdmin.Program [13] - Bitness: 64-bit
2018-09-15 01:02:17,212 INFO  XenAdmin.Program [13] - Log Application State
2018-09-15 01:02:17,212 INFO  XenAdmin.Program [13] - ExitCode: 0
2018-09-15 01:02:17,212 INFO  XenAdmin.Program [13] - Time since process started: 00:02:29.1593754
2018-09-15 01:02:17,213 ERROR XenAdmin.InvokeHelper [Main program thread] - Exception in Invoke
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.TabPages.GeneralTabPage.PoolAdditionalLicenseString()
   at XenAdmin.TabPages.GeneralTabPage.generateGeneralBox()
   at XenAdmin.TabPages.GeneralTabPage.BuildList()
   at System.Action.Invoke()
   at XenAdmin.OtherConfigAndTagsWatcher.OnTagsChanged()
   at XenAdmin.OtherConfigAndTagsWatcher.<>c.<connection_ConnectionStateChanged>b__25_0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at XenAdmin.InvokeHelper.<>c__DisplayClass4_0.<Invoke>b__0()
2018-09-15 01:02:17,213 ERROR XenAdmin.Program [Main program thread] - Exception in Invoke
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.TabPages.GeneralTabPage.PoolAdditionalLicenseString()
   at XenAdmin.TabPages.GeneralTabPage.generateGeneralBox()
   at XenAdmin.TabPages.GeneralTabPage.BuildList()
   at System.Action.Invoke()
   at XenAdmin.OtherConfigAndTagsWatcher.OnTagsChanged()
   at XenAdmin.OtherConfigAndTagsWatcher.<>c.<connection_ConnectionStateChanged>b__25_0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at XenAdmin.InvokeHelper.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at XenAdmin.Program.<>c__DisplayClass66_0.<Invoke>b__0()
2018-09-15 01:02:17,213 FATAL XenAdmin.Program [Connection to 192.168.5.65] - Uncaught exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XenAdmin.Program.Invoke(Control c, Delegate f, Object[] p)
   at XenAdmin.MainWindow.System.ComponentModel.ISynchronizeInvoke.Invoke(Delegate method, Object[] args)
   at XenAdmin.OtherConfigAndTagsWatcher.connection_ConnectionStateChanged(Object sender, EventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at XenAdmin.Network.XenConnection.OnConnectionStateChanged()
   at XenAdmin.Network.XenConnection.EndConnect(Boolean clearCache, ConnectTask task, Boolean exiting)
   at XenAdmin.Network.XenConnection.HandleConnectionLost(ConnectTask task, Pool pool, String poolopaqueref)
   at XenAdmin.Network.XenConnection.HandleConnectionResult(ConnectTask task, Exception error, Pool pool)
   at XenAdmin.Network.XenConnection.ConnectWorkerThread(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
2018-09-15 01:02:17,213 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Version: 7.5.0.8
2018-09-15 01:02:17,213 INFO  XenAdmin.Program [Connection to 192.168.5.65] - .NET runtime version: 4.0.30319.42000
2018-09-15 01:02:17,213 INFO  XenAdmin.Program [Connection to 192.168.5.65] - OS version: Microsoft Windows NT 10.0.17134.0
2018-09-15 01:02:17,213 INFO  XenAdmin.Program [Connection to 192.168.5.65] - UI Culture: English (United States)
2018-09-15 01:02:17,213 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Bitness: 64-bit
2018-09-15 01:02:17,213 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Log Application State
2018-09-15 01:02:17,213 INFO  XenAdmin.Program [Connection to 192.168.5.65] - ExitCode: 0
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Time since process started: 00:02:29.1603460
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Handles open: 1013
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - USER handles open: 336
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - GDI handles open: 120
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Thread count: 33
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Virtual memory size: 39673815040 B(36.9 GB)
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Working set: 155693056 B(148 MB)
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Private memory size: 105222144 B(100 MB)
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Nonpaged system memory size: 75920 B(74 kB)
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Paged memory size: 105222144 B(100 MB)
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Paged system memory size: 936280 B(914 kB)
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Peak paged memory size: 106668032 B(102 MB)
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Peak virtual memory size: 39674093568 B(36.9 GB)
2018-09-15 01:02:17,214 INFO  XenAdmin.Program [13] - Peak working set: 156463104 B(149 MB)
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [13] - Process priority class: Normal
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [13] - Privileged processor time: 00:00:03.1718750
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [13] - Total processor time: 00:00:08.1875000
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [13] - User processor time: 00:00:05.0156250
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Handles open: 1014
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - USER handles open: 336
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - GDI handles open: 121
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Thread count: 33
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Virtual memory size: 39673880576 B(36.9 GB)
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Working set: 156213248 B(149 MB)
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Private memory size: 105676800 B(101 MB)
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Nonpaged system memory size: 76056 B(74 kB)
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Paged memory size: 105676800 B(101 MB)
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Paged system memory size: 936280 B(914 kB)
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Peak paged memory size: 106668032 B(102 MB)
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Peak virtual memory size: 39674093568 B(36.9 GB)
2018-09-15 01:02:17,215 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Peak working set: 156463104 B(149 MB)
2018-09-15 01:02:17,216 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Process priority class: Normal
2018-09-15 01:02:17,216 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Privileged processor time: 00:00:03.1718750
2018-09-15 01:02:17,216 INFO  XenAdmin.Program [Connection to 192.168.5.65] - Total processor time: 00:00:08.1875000
2018-09-15 01:02:17,216 INFO  XenAdmin.Program [Connection to 192.168.5.65] - User processor time: 00:00:05.0156250

```

# Hardware and Software

 - Hardware: 3x Dell R610 II
 - Host XCP-ng Version: 7.5.0 (up-to-date as of 15Sep@0030CDT)
 - Client XCP-ng Center Version: 7.5.0.8
 - Desktop OS: Windows 10 Pro 1803

# Thoughts

The issue appears to be the Client attempting to query the License status of the former master after it has been disconnected from the pool, resulting in an unhandled `NULL` result.

**Comment by borzel** [comment]
Can you please try your case again with XCP-ng Center 7.5.1? We fixed a null-Pointer that may caused your issue.

**Comment by borzel** [comment]
@wranders I assume it is resolved... if not, please reopen the issue here
