### ISSUE TITLE
Error while importing OVA template

### ISSUE THREAD

**Issue by inat3k** [xcp-ng/xenadmin#107]
**Describe the bug**
NullReferenceException while importing OVA file in XCP-NG Center 7.5.1.12

**To Reproduce**
1. Right click on xenserver item
2. Click on 'Import...'
3. Select OVA file
4. Click next until 'Storage' tab
5. See error

**Screenshots / Logfiles**

```
2018-09-26 10:26:40,390 INFO  XenAdmin.Network.XenConnection [10] - Connection to 192.168.1.190 successful.
2018-09-26 10:26:52,240 INFO  XenOvf.OVF [Main program thread] - Import.Process: Found a VMWare Virtual Hardware Section (Rating: 4) [vmx-08]
2018-09-26 10:26:54,753 FATAL XenAdmin.Program [Main program thread] - Uncaught exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.Wizards.ImportWizard.OvfStorageResource.get_RequiredDiskCapacity()
   at XenAdmin.Wizards.GenericPages.SelectVMStorageWithMultipleVirtualDisksPage.PopulateSrComboBox(List`1 commonSRs)
   at XenAdmin.Wizards.GenericPages.SelectVMStorageWithMultipleVirtualDisksPage.PopulatePage()
   at XenAdmin.Controls.XenTabPage.PageLoaded(PageLoadedDirection direction)
   at XenAdmin.Wizards.XenWizardBase.WizardProgress_EnteringStep(Object sender, WizardProgressEventArgs e)
   at XenAdmin.Wizards.WizardProgress.OnEnteringStep(Boolean isForwardsTransition)
   at XenAdmin.Wizards.WizardProgress.NextStep()
   at XenAdmin.Wizards.XenWizardBase.buttonNext_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Version: 7.5.1.12
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - .NET runtime version: 4.0.30319.42000
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - OS version: Microsoft Windows NT 10.0.17134.0
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - UI Culture: English (United States)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Bitness: 64-bit
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Log Application State
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - ExitCode: 0
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Time since process started: 00:00:38.5018588
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Handles open: 1311
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - USER handles open: 444
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - GDI handles open: 179
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Thread count: 50
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Virtual memory size: 39722213376 B(37 GB)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Working set: 174850048 B(167 MB)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Private memory size: 109400064 B(104 MB)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Nonpaged system memory size: 95128 B(93 kB)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Paged memory size: 109400064 B(104 MB)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Paged system memory size: 981976 B(959 kB)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Peak paged memory size: 115494912 B(110 MB)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Peak virtual memory size: 39780978688 B(37 GB)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Peak working set: 179552256 B(171 MB)
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Process priority class: Normal
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Privileged processor time: 00:00:02.3437500
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - Total processor time: 00:00:06.6406250
2018-09-26 10:26:54,784 INFO  XenAdmin.Program [Main program thread] - User processor time: 00:00:04.2968750
```

**Hard-/Software involved:**
 - Hardware: HP ProLiant ML350p G8
 - Host XCP-ng Version: 7.5
 - Client XCP-ng Center Version: 7.5.1.12
 - Desktop OS: Windows 10 1803

**Comment by cocoon** [comment]
Can you tell more about the OVA you was trying to import?
Is it something public that can be analysed?

I expect it to fail, too, if using Citrix Xen Center 7.5 + Xen Server?


Interesting in your logs:

`Found a VMWare Virtual Hardware Section (Rating: 4) [vmx-08]`

**Comment by borzel** [comment]
@inat3k issue resolved ❓

**Comment by borzel** [comment]
@inat3k please reopen the issue if you need to
