### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by hoerup** [xcp-ng/xenadmin#150]
XCP-ng center crashes on launch

2019-04-29 17:23:40,881 FATAL XenAdmin.Program [Main program thread] - Uncaught exception
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at XenAdmin.XenSearch.Search.SearchFor(IXenObject value, QueryScope scope)
   at XenAdmin.Controls.MainWindowControls.NavigationPane.OnNavigationModeChanged()
   at System.Windows.Forms.ToolStripButton.set_CheckState(CheckState value)
   at System.Windows.Forms.ToolStripButton.set_Checked(Boolean value)
   at XenAdmin.Controls.MainWindowControls.NavigationPane..ctor()
   at XenAdmin.MainWindow.InitializeComponent()
   at XenAdmin.MainWindow..ctor(ArgType argType, String[] args)
   at XenAdmin.Program.Main(String[] Args)
2019-04-29 17:23:40,881 INFO  XenAdmin.Program [Main program thread] - Version: 7.6.3.21
2019-04-29 17:23:40,881 INFO  XenAdmin.Program [Main program thread] - .NET runtime version: 4.0.30319.18449
2019-04-29 17:23:40,881 INFO  XenAdmin.Program [Main program thread] - OS version: Microsoft Windows NT 6.2.9200.0
2019-04-29 17:23:40,881 INFO  XenAdmin.Program [Main program thread] - UI Culture: English (United States)
2019-04-29 17:23:40,881 INFO  XenAdmin.Program [Main program thread] - Bitness: 64-bit
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Log Application State
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - ExitCode: 0
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Time since process started: 00:00:01.6691019
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Handles open: 517
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - USER handles open: 62
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - GDI handles open: 54
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Thread count: 19
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Virtual memory size: 2902097920 B(2.7 GB)
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Working set: 72781824 B(69 MB)
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Private memory size: 49123328 B(47 MB)
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Nonpaged system memory size: 57800 B(56 kB)
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Paged memory size: 49123328 B(47 MB)
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Paged system memory size: 614848 B(600 kB)
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Peak paged memory size: 66420736 B(63 MB)
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Peak virtual memory size: 2914119680 B(2.7 GB)
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Peak working set: 88334336 B(84 MB)
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Process priority class: Normal
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Privileged processor time: 00:00:00.0780005
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - Total processor time: 00:00:01.6380105
2019-04-29 17:23:40,897 INFO  XenAdmin.Program [Main program thread] - User processor time: 00:00:01.5600100

**Comment by borzel** [comment]
Please upgrade to latest .net 4.7 and try again.

**Comment by schulz-alexander** [comment]
@hoerup is your issue fixed with the update of .net?

**Comment by schulz-alexander** [comment]
No responce, I close. Feel free to reopen if needed.
