### ISSUE TITLE
Unexpected Error: Key not valid for use in specified state.

### ISSUE THREAD

**Issue by rwarford** [xcp-ng/xenadmin#185]
**Describe the bug**

**To Reproduce**
1. Start XCP-NG Server
2. See error

**Expected behavior**
I get a message that an "Unexpected Error" has occurred.  If I click OK I have to re-add my servers but then everything appears to work correctly.

**Screenshots / Logfiles**
If applicable, add screenshots / logfiles to help explain your problem.

Log file:
020-04-16 20:57:57,901 FATAL XenAdmin.Program [Main program thread] - Uncaught exception
System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at XenCenterLib.EncryptionUtils.Unprotect(String protectedstring)
   at XenAdmin.Core.HealthCheck.SendProxySettingsToHealthCheck()
   at XenAdmin.MainWindow.MainWindow_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at XenAdmin.MainWindow.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
2020-04-16 20:57:57,904 INFO  XenAdmin.Program [Main program thread] - Version: 20.4.0.32
2020-04-16 20:57:57,904 INFO  XenAdmin.Program [Main program thread] - .NET runtime version: 4.0.30319.42000
2020-04-16 20:57:57,904 INFO  XenAdmin.Program [Main program thread] - OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
2020-04-16 20:57:57,904 INFO  XenAdmin.Program [Main program thread] - UI Culture: English (United States)
2020-04-16 20:57:57,904 INFO  XenAdmin.Program [Main program thread] - Bitness: 64-bit
2020-04-16 20:57:57,906 INFO  XenAdmin.Program [Main program thread] - Log Application State
2020-04-16 20:57:57,906 INFO  XenAdmin.Program [Main program thread] - ExitCode: 0
2020-04-16 20:57:57,906 INFO  XenAdmin.Program [Main program thread] - Time since process started: 00:00:02.8681641
2020-04-16 20:57:57,906 INFO  XenAdmin.Program [Main program thread] - Handles open: 551
2020-04-16 20:57:57,907 INFO  XenAdmin.Program [Main program thread] - USER handles open: 148
2020-04-16 20:57:57,907 INFO  XenAdmin.Program [Main program thread] - GDI handles open: 90
2020-04-16 20:57:57,907 INFO  XenAdmin.Program [Main program thread] - Thread count: 28
2020-04-16 20:57:57,908 INFO  XenAdmin.Program [Main program thread] - Virtual memory size: 2943905792 B(2.7 GB)
2020-04-16 20:57:57,908 INFO  XenAdmin.Program [Main program thread] - Working set: 103329792 B(99 MB)
2020-04-16 20:57:57,908 INFO  XenAdmin.Program [Main program thread] - Private memory size: 75055104 B(72 MB)
2020-04-16 20:57:57,908 INFO  XenAdmin.Program [Main program thread] - Nonpaged system memory size: 52520 B(51 kB)
2020-04-16 20:57:57,908 INFO  XenAdmin.Program [Main program thread] - Paged memory size: 75055104 B(72 MB)
2020-04-16 20:57:57,909 INFO  XenAdmin.Program [Main program thread] - Paged system memory size: 649048 B(634 kB)
2020-04-16 20:57:57,909 INFO  XenAdmin.Program [Main program thread] - Peak paged memory size: 76128256 B(73 MB)
2020-04-16 20:57:57,909 INFO  XenAdmin.Program [Main program thread] - Peak virtual memory size: 2944430080 B(2.7 GB)
2020-04-16 20:57:57,909 INFO  XenAdmin.Program [Main program thread] - Peak working set: 103813120 B(99 MB)
2020-04-16 20:57:57,909 INFO  XenAdmin.Program [Main program thread] - Process priority class: Normal
2020-04-16 20:57:57,909 INFO  XenAdmin.Program [Main program thread] - Privileged processor time: 00:00:00.3588023
2020-04-16 20:57:57,909 INFO  XenAdmin.Program [Main program thread] - Total processor time: 00:00:02.5272162
2020-04-16 20:57:57,909 INFO  XenAdmin.Program [Main program thread] - User processor time: 00:00:02.1684139

**Hard-/Software involved:**
 - Hardware: [e.g. Dell M620]
 - Host XCP-ng Version: [e.g. 7.4.1]
 - Client XCP-ng Center Version: [e.g. 7.4.2-RC2]
 - Desktop OS: [e.g. Windows 10 1803]

**Additional context**

I tried re-installing but there was no change in behavior.

**Comment by cocoon** [comment]
@rwarford Hi, can you give some more details about the environment?

As I can see from the logs you are using the latest XCP-ng Center release, right?
20.4.0.32

Your Windows Client is Windows 7?

What version and where is your XCP-ng Servers are running?
Hardware: ?
Host XCP-ng Version: ?

Are you connecting to a single server or to a pool?


**What you can already try is to:**

-  close XCP-ng Center
- Open %AppData% in Explorer (should bring you to something like C:\Users\**[YOURUSER]**\AppData\Roaming: )

- Backup the XCP-ng folder in that directory

- rename or delete the XCP-ng folder

- start XCP-ng Center again, it should now create a new folder with a new configuration

If that is not chaning anything we might need a Windows 7 test machine and whatever XCP-ng Server version you are using to try to generate the same error or blindly fix whatever is in "SendProxySettingsToHealthCheck" ... 
https://github.com/xcp-ng/xenadmin/blob/development/XenAdmin/MainWindow.cs#L545


Do you remember to have anything enabled with Health-Check? It should not be possible but I never used it ...

Or anything with proxies? Any special additional options?

**Comment by rwarford** [comment]
Deleting the XCP-ng folder fixed the issue (why didn't I think of that?).  Thank you!

FWIW:
- XCP-ng center host is Windows 7.
- XCP-ng center version 20.4.0.32.
- Host version XCP-ng Host 7.5.0,
- Hosts are Dell R710 and R410s.
- Servers are pooled.

**Comment by cocoon** [comment]
Great and thanks for reporting back.
OK I think I can close this then.
