### ISSUE TITLE
Error when trying to look at memory consumption of the host

### ISSUE THREAD

**Issue by JoeArnon** [xcp-ng/xenadmin#205]
```
2021-07-25 15:47:06,668 FATAL XenAdmin.Program [Main program thread] - Uncaught exception
System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at XenAdmin.TabPages.BallooningPage.SetupDeprecationBanner()
   at XenAdmin.TabPages.BallooningPage.Rebuild()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
2021-07-25 15:47:06,672 INFO  XenAdmin.Program [Main program thread] - Version: 20.3.0.29
2021-07-25 15:47:06,672 INFO  XenAdmin.Program [Main program thread] - .NET runtime version: 4.0.30319.42000
2021-07-25 15:47:06,672 INFO  XenAdmin.Program [Main program thread] - OS version: Microsoft Windows NT 10.0.19042.0
2021-07-25 15:47:06,672 INFO  XenAdmin.Program [Main program thread] - UI Culture: English (United States)
2021-07-25 15:47:06,672 INFO  XenAdmin.Program [Main program thread] - Bitness: 64-bit
2021-07-25 15:47:06,673 INFO  XenAdmin.Program [Main program thread] - Log Application State
2021-07-25 15:47:06,673 INFO  XenAdmin.Program [Main program thread] - ExitCode: 0
2021-07-25 15:47:06,673 INFO  XenAdmin.Program [Main program thread] - Time since process started: 00:01:08.0849112
2021-07-25 15:47:06,676 INFO  XenAdmin.Program [Main program thread] - Handles open: 1036
2021-07-25 15:47:06,676 INFO  XenAdmin.Program [Main program thread] - USER handles open: 773
2021-07-25 15:47:06,676 INFO  XenAdmin.Program [Main program thread] - GDI handles open: 113
2021-07-25 15:47:06,676 INFO  XenAdmin.Program [Main program thread] - Thread count: 34
2021-07-25 15:47:06,676 INFO  XenAdmin.Program [Main program thread] - Virtual memory size: 39640780800 B(36.9 GB)
2021-07-25 15:47:06,676 INFO  XenAdmin.Program [Main program thread] - Working set: 203542528 B(194 MB)
2021-07-25 15:47:06,676 INFO  XenAdmin.Program [Main program thread] - Private memory size: 140566528 B(134 MB)
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - Nonpaged system memory size: 83408 B(81 kB)
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - Paged memory size: 140566528 B(134 MB)
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - Paged system memory size: 828360 B(809 kB)
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - Peak paged memory size: 146313216 B(140 MB)
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - Peak virtual memory size: 39642198016 B(36.9 GB)
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - Peak working set: 205193216 B(196 MB)
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - Process priority class: Normal
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - Privileged processor time: 00:00:01.9843750
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - Total processor time: 00:00:06.7500000
2021-07-25 15:47:06,677 INFO  XenAdmin.Program [Main program thread] - User processor time: 00:00:04.7656250
```

**Comment by JoeArnon** [comment]
![error](https://user-images.githubusercontent.com/6695277/126905704-2a536d71-3b0c-4d3d-8481-87cad7b7c296.png)

**Comment by cocoon** [comment]
Hi, I see that you are using an old version (Version: 20.3.0.29), does it still occur if you use the latest one?

https://github.com/xcp-ng/xenadmin/releases/tag/v20.04.01.33

Was fixed here:
https://github.com/xcp-ng/xenadmin/issues/184

**Comment by JoeArnon** [comment]
No, it seems to be fixed on the new version.

Thanks,

Joe
