### ISSUE TITLE
xcp-ng center unexpected error 

### ISSUE THREAD

**Issue by linspinho** [xcp-ng/xenadmin#82]
Hello, I got unexpected error running xcp-ng center after installation, the log:

2018-07-23 13:58:04,020 INFO  Audit [1] - Operation started: TransferXenCenterMetadataAction: Connection unknown: Transfer Health Check settings
2018-07-23 13:58:04,269 INFO  Audit [8] - Operation success: TransferXenCenterMetadataAction: Connection unknown: Transfer Health Check settings
2018-07-23 13:58:04,425 INFO  XenAdmin.Program [Main program thread] - Application started
2018-07-23 13:58:04,425 INFO  XenAdmin.Program [Main program thread] - Version: 7.5.0.5
2018-07-23 13:58:04,425 INFO  XenAdmin.Program [Main program thread] - .NET runtime version: 4.0.30319.34209
2018-07-23 13:58:04,425 INFO  XenAdmin.Program [Main program thread] - OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
2018-07-23 13:58:04,425 INFO  XenAdmin.Program [Main program thread] - UI Culture: English (United States)
2018-07-23 13:58:04,425 INFO  XenAdmin.Program [Main program thread] - Bitness: 64-bit
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsDialog [Main program thread] - Tools Options Settings -
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConnectionOptionsPage [Main program thread] - Connection Tab Settings -
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConnectionOptionsPage [Main program thread] - === ProxySetting: 0
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConnectionOptionsPage [Main program thread] - === ProxyAddress: 
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConnectionOptionsPage [Main program thread] - === ProxyPort: 80
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConnectionOptionsPage [Main program thread] - === ByPassProxyForServers: False
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConnectionOptionsPage [Main program thread] - === ProvideProxyAuthentication: False
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConnectionOptionsPage [Main program thread] - === ProxyAuthenticationMethod: 1
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConnectionOptionsPage [Main program thread] - === ConnectionTimeout: 20000
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - Console Tab Settings -
2018-07-23 13:58:04,425 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === FullScreenShortcutKey: 3
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === DockShortcutKey: 1
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === UncaptureShortcutKey: 0
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === ClipboardAndPrinterRedirection: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === WindowsShortcuts: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === ReceiveSoundFromRDP: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === AutoSwitchToRDP: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === ConnectToServerConsole: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === PreserveScaleWhenUndocked: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.ConsolesOptionsPage [Main program thread] - === PreserveScaleWhenSwitchBackToVNC: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.SecurityOptionsPage [Main program thread] - === WarnUnrecognizedCertificate: False
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.SecurityOptionsPage [Main program thread] - === WarnChangedCertificate: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.UpdatesOptionsPage [Main program thread] - === AllowXenCenterUpdates: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.UpdatesOptionsPage [Main program thread] - === AllowPatchesUpdates: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.UpdatesOptionsPage [Main program thread] - === AllowXenServerUpdates: False
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.DisplayOptionsPage [Main program thread] - === FillAreaUnderGraphs: False
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.DisplayOptionsPage [Main program thread] - === ShowHostOnlyInSearch: False
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.SaveAndRestoreOptionsPage [Main program thread] - === SaveSession: True
2018-07-23 13:58:04,441 INFO  XenAdmin.Dialogs.OptionsPages.SaveAndRestoreOptionsPage [Main program thread] - === RequirePass: False
2018-07-23 13:58:04,488 INFO  XenAdmin.Dialogs.OptionsPages.PluginOptionsPage [Main program thread] - === DisabledPlugins: <None>
2018-07-23 13:58:04,488 INFO  XenAdmin.Dialogs.OptionsPages.ConfirmationOptionsPage [Main program thread] - === DoNotConfirmDismissAlerts: False
2018-07-23 13:58:04,488 INFO  XenAdmin.Dialogs.OptionsPages.ConfirmationOptionsPage [Main program thread] - === DoNotConfirmDismissUpdates: False
2018-07-23 13:58:04,488 INFO  XenAdmin.Dialogs.OptionsPages.ConfirmationOptionsPage [Main program thread] - === DoNotConfirmDismissEvents: False
2018-07-23 13:58:04,488 INFO  XenAdmin.Program [Main program thread] - Connecting to pipe '\\.\pipe\XenCenter-1-MJRN-C:-Program Files (x86)-XCP-ng Center-XenCenterMain.exe'
2018-07-23 13:58:04,488 INFO  XenAdmin.Program [Main program thread] - Successfully created pipe '\\.\pipe\XenCenter-1-MJRN-C:-Program Files (x86)-XCP-ng Center-XenCenterMain.exe' - proceeding to launch XenCenter
2018-07-23 13:58:07,374 FATAL XenAdmin.Program [Main program thread] - Uncaught exception
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at XenAdmin.XenSearch.Search.SearchFor(IXenObject value, QueryScope scope)
   at XenAdmin.Controls.MainWindowControls.NavigationPane.OnNavigationModeChanged()
   at System.Windows.Forms.ToolStripButton.set_CheckState(CheckState value)
   at System.Windows.Forms.ToolStripButton.set_Checked(Boolean value)
   at XenAdmin.Controls.MainWindowControls.NavigationPane..ctor()
   at XenAdmin.MainWindow.InitializeComponent()
   at XenAdmin.MainWindow..ctor(ArgType argType, String[] args)
   at XenAdmin.Program.Main(String[] Args)
2018-07-23 13:58:07,389 INFO  XenAdmin.Program [Main program thread] - Version: 7.5.0.5
2018-07-23 13:58:07,389 INFO  XenAdmin.Program [Main program thread] - .NET runtime version: 4.0.30319.34209
2018-07-23 13:58:07,389 INFO  XenAdmin.Program [Main program thread] - OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
2018-07-23 13:58:07,389 INFO  XenAdmin.Program [Main program thread] - UI Culture: English (United States)
2018-07-23 13:58:07,389 INFO  XenAdmin.Program [Main program thread] - Bitness: 64-bit
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Log Application State
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - ExitCode: 0
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Time since process started: 00:00:05.2104091
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Handles open: 422
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - USER handles open: 66
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - GDI handles open: 61
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Thread count: 21
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Virtual memory size: 781185024 B(745 MB)
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Working set: 97779712 B(93 MB)
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Private memory size: 61349888 B(59 MB)
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Nonpaged system memory size: 58656 B(57 kB)
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Paged memory size: 61349888 B(59 MB)
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Paged system memory size: 613672 B(599 kB)
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Peak paged memory size: 78258176 B(75 MB)
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Peak virtual memory size: 793153536 B(756 MB)
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Peak working set: 113623040 B(108 MB)
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Process priority class: Normal
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Privileged processor time: 00:00:00.4524029
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - Total processor time: 00:00:02.1840140
2018-07-23 13:58:07,405 INFO  XenAdmin.Program [Main program thread] - User processor time: 00:00:01.7316111

I have downloaded the XCP-ng-center-7.5.0.msi, installed and when running the first time it failed.

 Desktop OS: Windows 7 Professional

**Comment by borzel** [comment]
Pleas update to a newer .Net Version, you are running .Net 4.5.2. Windows Update should provide you a newer version.

**Comment by borzel** [comment]
Please give feedback, in any case :-)

**Comment by linspinho** [comment]
@borzel thanks, it is working now!
