### ISSUE TITLE
Error when restarting toolstack

### ISSUE THREAD

**Issue by Danp2** [xcp-ng/xenadmin#89]
**Describe the bug**
XCP-ng Center crashes when restarting toolstack

**To Reproduce**
1. Launch XCP-ng Center
2. Select a server
3. Select Server > Restart Toolstack
4. Click 'Yes'

**Expected behavior**
Toolstack to restart and XCP-ng Center to successfully reconnect

**Screenshots / Logfiles**
![image](https://user-images.githubusercontent.com/7101313/43492711-d5bd5698-94ef-11e8-9c84-8261825cfe7e.png)

```
2018-07-31 18:27:31,362 INFO  XenAdmin.Program [23] - Version: 7.5.0.8
2018-07-31 18:27:31,362 INFO  XenAdmin.Program [23] - .NET runtime version: 4.0.30319.42000
2018-07-31 18:27:31,363 INFO  XenAdmin.Program [23] - OS version: Microsoft Windows NT 10.0.17134.0
2018-07-31 18:27:31,363 INFO  XenAdmin.Program [23] - UI Culture: English (United States)
2018-07-31 18:27:31,363 INFO  XenAdmin.Program [23] - Bitness: 64-bit
2018-07-31 18:27:31,366 INFO  XenAdmin.Program [23] - Log Application State
2018-07-31 18:27:31,366 INFO  XenAdmin.Program [23] - ExitCode: 0
2018-07-31 18:27:31,366 INFO  XenAdmin.Program [23] - Time since process started: 00:04:22.5202944
2018-07-31 18:27:31,373 INFO  XenAdmin.Program [23] - Handles open: 1011
2018-07-31 18:27:31,374 INFO  XenAdmin.Program [23] - USER handles open: 343
2018-07-31 18:27:31,374 INFO  XenAdmin.Program [23] - GDI handles open: 103
2018-07-31 18:27:31,374 INFO  XenAdmin.Program [23] - Thread count: 33
2018-07-31 18:27:31,375 INFO  XenAdmin.Program [23] - Virtual memory size: 39665569792 B(36.9 GB)
2018-07-31 18:27:31,375 INFO  XenAdmin.Program [23] - Working set: 154468352 B(147 MB)
2018-07-31 18:27:31,375 INFO  XenAdmin.Program [23] - Private memory size: 102440960 B(98 MB)
2018-07-31 18:27:31,375 INFO  XenAdmin.Program [23] - Nonpaged system memory size: 73496 B(72 kB)
2018-07-31 18:27:31,375 INFO  XenAdmin.Program [23] - Paged memory size: 102440960 B(98 MB)
2018-07-31 18:27:31,375 INFO  XenAdmin.Program [23] - Paged system memory size: 931120 B(909 kB)
2018-07-31 18:27:31,375 INFO  XenAdmin.Program [23] - Peak paged memory size: 102965248 B(98 MB)
2018-07-31 18:27:31,375 INFO  XenAdmin.Program [23] - Peak virtual memory size: 39671209984 B(36.9 GB)
2018-07-31 18:27:31,375 INFO  XenAdmin.Program [23] - Peak working set: 154963968 B(148 MB)
2018-07-31 18:27:31,376 INFO  XenAdmin.Program [23] - Process priority class: Normal
2018-07-31 18:27:31,376 INFO  XenAdmin.Program [23] - Privileged processor time: 00:00:08.4062500
2018-07-31 18:27:31,376 INFO  XenAdmin.Program [23] - Total processor time: 00:00:19.9687500
2018-07-31 18:27:31,376 INFO  XenAdmin.Program [23] - User processor time: 00:00:11.5625000
2018-07-31 18:27:31,408 ERROR XenAdmin.InvokeHelper [Main program thread] - Exception in Invoke
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.TabPages.GeneralTabPage.PoolAdditionalLicenseString()
   at XenAdmin.TabPages.GeneralTabPage.generateGeneralBox()
   at XenAdmin.TabPages.GeneralTabPage.BuildList()
   at System.Action.Invoke()
   at XenAdmin.OtherConfigAndTagsWatcher.OnTagsChanged()
   at XenAdmin.OtherConfigAndTagsWatcher.<>c.<connection_ConnectionStateChanged>b__25_0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at XenAdmin.InvokeHelper.<>c__DisplayClass4_0.<Invoke>b__0()
2018-07-31 18:27:31,408 ERROR XenAdmin.Program [Main program thread] - Exception in Invoke
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.TabPages.GeneralTabPage.PoolAdditionalLicenseString()
   at XenAdmin.TabPages.GeneralTabPage.generateGeneralBox()
   at XenAdmin.TabPages.GeneralTabPage.BuildList()
   at System.Action.Invoke()
   at XenAdmin.OtherConfigAndTagsWatcher.OnTagsChanged()
   at XenAdmin.OtherConfigAndTagsWatcher.<>c.<connection_ConnectionStateChanged>b__25_0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at XenAdmin.InvokeHelper.<>c__DisplayClass4_0.<Invoke>b__0()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at XenAdmin.Program.<>c__DisplayClass66_0.<Invoke>b__0()
2018-07-31 18:27:31,409 FATAL XenAdmin.Program [Connection to 192.168.1.21] - Uncaught exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XenAdmin.Program.Invoke(Control c, Delegate f, Object[] p)
   at XenAdmin.MainWindow.System.ComponentModel.ISynchronizeInvoke.Invoke(Delegate method, Object[] args)
   at XenAdmin.OtherConfigAndTagsWatcher.connection_ConnectionStateChanged(Object sender, EventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at XenAdmin.Network.XenConnection.OnConnectionStateChanged()
   at XenAdmin.Network.XenConnection.EndConnect(Boolean clearCache, ConnectTask task, Boolean exiting)
   at XenAdmin.Network.XenConnection.HandleConnectionLost(ConnectTask task, Pool pool, String poolopaqueref)
   at XenAdmin.Network.XenConnection.HandleConnectionResult(ConnectTask task, Exception error, Pool pool)
   at XenAdmin.Network.XenConnection.ConnectWorkerThread(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Hard-/Software involved:**
 - Hardware: Dell R620
 - Host XCP-ng Version: 7.4.1, fully patched
 - Client XCP-ng Center Version: 7.5.0.8
 - Desktop OS: Windows 10 1803 (17134.191)

**Additional context**
Program also crashes if the toolstack is restarted elsewhere, such as XO

**Comment by borzel** [comment]
Host XCP-ng Version: 7.4.1 <-> Client XCP-ng Center Version: 7.5.0.8

Maybe this is the problem... hhmm...

Note to myself: Check Client API Version

**Comment by borzel** [comment]
@Danp2 can you please try to update your host to XCP-ng 7.5?

**Comment by Danp2** [comment]
@borzel I just upgraded to 7.5 and the error persists. I will check again after applying all patches.

**Comment by Danp2** [comment]
Still crashes even after all patches are applied. ☹️

**Comment by Danp2** [comment]
Seems better, although it did still crash once or twice while testing this.

**Comment by cocoon** [comment]
So we would need logs again, where it crashes.
And what is your envrionment, what Server and from where do you connect, how is the network connection between Client and Server?

Because it looks like it tries to access information from the server while it is not available somehow ... never have seen this happen before and can't reproduce it here.

**Comment by borzel** [comment]
I could also not reproduce your issue :-(

**Comment by Danp2** [comment]
New log attached. Running fully patched XCP-ng 7.5 on Dell PE R620. Client and server are connected by a Powerconnect 2724 switch.

[XCP-ng Center.log](https://github.com/xcp-ng/xenadmin/files/2345681/XCP-ng.Center.log)

**Comment by cocoon** [comment]
OK, so it's the same error again, so I did not catch the right object.
Will try something again later.

So this is a single host that is NOT part of a pool?
Do you manage multiple servers with the crashing client or only this single server?

**Comment by Danp2** [comment]
Oh... I guess I failed to run the test client. Sorry about that. I'll try again with the new version and report back if the error reoccurs.

**Comment by cocoon** [comment]
Just to ask: was closing this issue on purpose? 
Is the problem solved? 

If yes, with the original XCP-NG Center and the problem was something else?

Or was it fixed with changes from the test version? Because without confirmation none of those changes would be integrated into the official XCP-NG Center ,it was only in a test build for now. 

Just to be sure.

**Comment by Danp2** [comment]
@cocoon I closed the issue because I wasn't able to duplicate the issue in the test builds.

**Comment by cocoon** [comment]
OK thanks good to know.

One last important information I would need:
Do you still have the first testbuild that I creaded and tested it with that, too? Because this would be the one how I would like to fix it.

The second one was wit mouch more code removed to check, if there are any other problems around it.

If you don't have the first one anymore, I can add it again.

**Comment by cocoon** [comment]
OK, I will try it with those changes. Thanks!
