### ISSUE TITLE
Unexpected error with proxy on 7.5.0.8

### ISSUE THREAD

**Issue by DoramGreenblat** [xcp-ng/xenadmin#95]
When connecting to an http proxy to manage xcp-ng, system crashes

**To Reproduce**
1. Go to 'open xcp-ng admin'
2. administer a resource only accessible via proxy'
3. Boot up a vm
4. See error and crash.

**Expected behavior**
Server boots

**Screenshots / Logfiles**
Logfile attached. The error appears to be a crash due to licensing and time.
```
08-22 17:24:29,717 WARN  XenAdmin.Network.XenConnection [Connection to 10.0.254.101] - Lost connection to 10.0.254.101
2018-08-22 17:24:29,771 ERROR XenAdmin.Dialogs.LicenseStatus [15] - Couldn't get the server time because: Value cannot be null.
Parameter name: System.Object
2018-08-22 17:24:29,771 ERROR XenAdmin.Utils.AsyncServerTime [15] - Failed to fetch server time for host as host could not be resolved
2018-08-22 17:24:29,774 ERROR XenAdmin.Controls.MainWindowControls.NavigationView [Main program thread] - System.NullReferenceException: Object reference not set to an instance of an object.
   at XenAdmin.TabPages.GeneralTabPage.PoolAdditionalLicenseString()
   at XenAdmin.TabPages.GeneralTabPage.generateGeneralBox()
   at XenAdmin.TabPages.GeneralTabPage.BuildList()
```

[XCP-ng Center.log](https://github.com/xcp-ng/xenadmin/files/2311013/XCP-ng.Center.log)

**Comment by borzel** [comment]
Can you please check, if this issue exists on XenServer 7.5 and XenCenter 7.5?

**Comment by DoramGreenblat** [comment]
Thanks for responding @borzel 
This can be replicated on Xencenter 7.5 and have opened request with xenserver.org https://bugs.xenserver.org/browse/XSO-892

**Comment by borzel** [comment]
Can you please try again with XCP-ng Center 7.5.1 and report if it's fixed with that?

**Comment by DoramGreenblat** [comment]
Hi Borzel. Thanks I tested tonight with Xencenter 7.6 and xcp-ng center 7.5.1
The Xencenter 7.6 works as expected. 
xcp-ng 7.5.1 is better, it does not crash completely, but disconnects from the pool.

I have provided a single login, connection and timeout. See log entry at timestamp: 21:51:52
[XCP-ng Center.log](https://github.com/xcp-ng/xenadmin/files/2416848/XCP-ng.Center.log)

**Comment by borzel** [comment]
@DoramGreenblat can you please test again with XCP-ng Center 7.6 nightly? -> https://schulzalex.de/builds/xcp-ng/7.6/

**Comment by DoramGreenblat** [comment]
Verified fix.  Exception no longer occurs.
